### PR TITLE
watermark

### PR DESCRIPTION
**Pull request by Jimmyqu**
add simple watermark function

### CODE REVIEW

**Comment by Zeyi-Lin** [comment]
Thank you for your contribution, I will test your PR today.

**Comment by Tobe2d** [comment]
Can you add support for other languages please? RTL

**Comment by Zeyi-Lin** [comment]
> Can you add support for other languages please? RTL

For example, what language?

You can pull the latest code or experience the demo at: https://huggingface.co/spaces/TheEeeeLin/HivisionIDPhotos. The watermark algorithm, fonts, and interactions have been improved.

**Comment by Zeyi-Lin** [comment]
> Arabic please

You can try the following steps:
1. Download a TFF format Arabic font package.
2. Place the font package in the `hivision/plugin/font` directory.
3. Edit line 32 of `hivision/plugin/watermark.py`, setting `font_size` to the name of the font package.

**Comment by Tobe2d** [comment]
I tested that but the text looks broken and r to LTR left while it should be RTL connected and Right to left

**Comment by Zeyi-Lin** [comment]
> I tested that but the text looks broken and r to LTR left while it should be RTL connected and Right to left

Is there a font file or screenshot?

**Comment by Tobe2d** [comment]
I tested it in the defualt font https://font.download/font/arial

I tested it with 2 fonts:
1 - ARIAL.TTF
2 - NotoSansArabic-Regular.ttf

the word I test is عربي 
it looks broken:
image

**Comment by Zeyi-Lin** [comment]
I tried using the Times-New-Roman.ttf font, and this is the approximate effect：

image

**Comment by Tobe2d** [comment]
Thank you so much for trying! 

In the image you attached it is broken as it is writing it from left to righ 
The correct is right to left
It should look like this: عربي

**Pull request merged**
